include:
  # 1. The USB Dongle (Acts as the Central Receiver)
  - board: nice_nano_v2
    shield: temper_dongle

  # 2. Left Keyboard Half (Peripheral)
  - board: nice_nano_v2/pinctrl_low_power
    shield: temper_left nice_view_adapter nice_view_gem

  # 3. Right Keyboard Half (Peripheral)
  - board: nice_nano_v2/pinctrl_low_power
    shield: temper_right nice_view_adapter nice_view_gem

  # 4. Settings Reset File (Just in case you need to clear flash memory)
  - board: nice_nano_v2/pinctrl_low_power
    shield: settings_reset
