---
include:
  # The physical Left Half (now demoted to a peripheral, with screens enabled)
  - board: nice_nano
    shield: temper_left nice_view_adapter nice_view_gem
    artifact-name: temper_left
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n

  # The physical Right Half (peripheral by default, with screens enabled)
  - board: nice_nano
    shield: temper_right nice_view_adapter nice_view_gem
    artifact-name: temper_right
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n

  # The Dongle (Uses the left shield's layout, but acts as the central brain)
  # (No screens appended here, as the dongle stays plugged into the PC)
  - board: nice_nano
    shield: temper_left
    artifact-name: temper_dongle
    cmake-args: -DCONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2

  # Generates the reset file automatically so you don't have to hunt for it
  - board: nice_nano
    shield: settings_reset
    artifact-name: settings_reset
